# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.2
#
# <auto-generated>
#
# Generated from file `Helloworld.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module helloworld
_M_helloworld = Ice.openModule('helloworld')
__name__ = 'helloworld'

_M_helloworld._t_Greeter = IcePy.defineValue('::helloworld::Greeter', Ice.Value, -1, (), False, True, None, ())

if 'GreeterPrx' not in _M_helloworld.__dict__:
    _M_helloworld.GreeterPrx = Ice.createTempClass()
    class GreeterPrx(Ice.ObjectPrx):

        def printString(self, s, context=None):
            return _M_helloworld.Greeter._op_printString.invoke(self, ((s, ), context))

        def printStringAsync(self, s, context=None):
            return _M_helloworld.Greeter._op_printString.invokeAsync(self, ((s, ), context))

        def begin_printString(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_helloworld.Greeter._op_printString.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_printString(self, _r):
            return _M_helloworld.Greeter._op_printString.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_helloworld.GreeterPrx.ice_checkedCast(proxy, '::helloworld::Greeter', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_helloworld.GreeterPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::helloworld::Greeter'
    _M_helloworld._t_GreeterPrx = IcePy.defineProxy('::helloworld::Greeter', GreeterPrx)

    _M_helloworld.GreeterPrx = GreeterPrx
    del GreeterPrx

    _M_helloworld.Greeter = Ice.createTempClass()
    class Greeter(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::helloworld::Greeter')

        def ice_id(self, current=None):
            return '::helloworld::Greeter'

        @staticmethod
        def ice_staticId():
            return '::helloworld::Greeter'

        def printString(self, s, current=None):
            raise NotImplementedError("servant method 'printString' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_helloworld._t_GreeterDisp)

        __repr__ = __str__

    _M_helloworld._t_GreeterDisp = IcePy.defineClass('::helloworld::Greeter', Greeter, (), None, ())
    Greeter._ice_type = _M_helloworld._t_GreeterDisp

    Greeter._op_printString = IcePy.Operation('printString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())

    _M_helloworld.Greeter = Greeter
    del Greeter

# End of module helloworld
